### PR TITLE
Php 8

### PR DESCRIPTION
**Pull request by b1rdex**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Build failed.

**Comment by b1rdex** [comment]
There is a problem in the BlockHash that's not related to PHP 7.4. It uses 16x16 matrix but tries to write to 17-th element of array.

**Comment by jenssegers** [comment]
Will check it out!

**Review by allanmcarvalho — APPROVED** [review]

**Review by allanmcarvalho — APPROVED** [review]

**Comment by sauron07** [comment]
Hello! Is there any news about merging it to master?

**Comment by allanmcarvalho** [comment]
I am waiting for this merge too... New projects with php 8 is impossible without use some tricks in composer.

**Comment by sinedoOo** [comment]
Any update here?

**Pull request closed without merging**
